version: '3.8'

services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: thinkalike
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword

volumes:
  postgres_data:
